platform:
  - x64

environment:
  global:
    MSYS2_BASEVER: 20150512
    MSYS2_ARCH: x86_64
  matrix:
    - HOST_ARCH_ARG: --host=x86_64-w64-mingw32
      ADD_PATH: /mingw64/bin
    - HOST_ARCH_ARG: --host=i686-w64-mingw32
      ADD_PATH: /mingw32/bin
    - HOST_ARCH_ARG: --enable-msvc
      ADD_PATH: /mingw64/bin

install:
  - C:\"Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
  - 7z x msys2.tar.xz
  - 7z x msys2.tar > NUL
  - msys64\usr\bin\bash -lc ""
  - msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy make wget tar patch dos2unix diffutils ca-certificates mingw-w64-i686-ca-certificates mingw-w64-x86_64-ca-certificates mingw-w64-i686-gcc mingw-w64-i686-gcc-fortran mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-fortran && break || sleep 15; done"

build_script:
  - msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools"
  - msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; BuildTools/get.dependencies.sh fetch --no-third-party"
  - msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; export PATH=$PATH:$ADD_PATH; BuildTools/get.dependencies.sh build --monolithic --no-thirdparty --build=x86_64-w64-mingw32 $HOST_ARCH_ARG --test"

test: off